#!/usr/bin/env bash
# sets up two servers to be identical

# sets up nginx
apt-get update &&
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /custom_404.html;
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html; location = /custom_404.html { root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
sed -i "http {/a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
service nginx start