#!/usr/bin/env bash
# setup HAProxy 2.0-stable (LTS)
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
printf "\nfrontend haproxynode\nbind *:80\nmode http\ndefault_backend backendnodes\n" >> /etc/haproxy/haproxy.cfg
printf "\nbackend backendnodes\nbalance roundrobin\nserver 655-web-01 35.196.125.111\nserver 655-web-02 35.185.45.37\n" >> /etc/haproxy/haproxy.cfg
service haproxy start
