#!/usr/bin/env bash
#superstitious numbers
n=0
while (( n < 20))
do
    n=$(( n+1 ))
    if [ $n = 5 ]
    then
        echo "bad luck from China"
    elif [ $n = 10 ]
    then
        echo "bad luck from Japan"
    elif [ $n = 18 ]
    then
        echo "bad luck from Italy"
    fi
    echo $n
done
