#!/usr/bin/env bash
#clock
hour=0
minute=1
echo "Hour: "$hour
while ((hour < 12))
do
    echo $minute
    if [ $minute = 59 ]
    then
        minute=0
        hour=$((hour+1))
        echo "Hour: "$hour
    fi
    minute=$((minute+1))
done