#!/usr/bin/env bash
#clock
hour=0
minute=60
while ((hour <= 12))
do
    if [ $minute = 60 ]
    then
        minute=1
        echo "Hour: "$hour
        hour=$((hour+1))
    fi
    if ((hour <= 12))
    then
        echo $minute
    fi
    minute=$((minute+1))
done