#!/usr/bin/env bash
#sets localhost and facebook.com ips
cp /etc/hosts ~/host.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/host.new
sed -i '/localhost/a 8.8.8.8    facebook.com' ~/host.new
cp -f ~/host.new /etc/hosts
